### ISSUE TITLE
SVG Versionen

### ISSUE THREAD

**Issue by gravidigit** [inventwo/ioBroker.vis-icontwo#1]
Vielen Dank für den Adapter!

Ist eine SVG Version der Bilder geplant? Dies hat den Vorteil das man die Bilder auch über die VIS Einstellungen Färben kann. Ich habe bisher nur PNG und JPG Bilder gefunden. Danke!

**Comment by jkvarel** [comment]
Hallo @gravidigit , geplant: ja.

Wann das passieren wird wissen wir selber noch nicht :)

**Comment by skvarel** [comment]
> 
> 
> Vielen Dank für den Adapter!
> 
> Ist eine SVG Version der Bilder geplant? Dies hat den Vorteil das man die Bilder auch über die VIS Einstellungen Färben kann. Ich habe bisher nur PNG und JPG Bilder gefunden. Danke!

Die PNG Icons sind nun in unseren Widgets frei einzufärben (ab Version 2.4.3 latest)

**Comment by vonCartman** [comment]
@skvarel kannst du kurz sagen, wie es funktioniert mit umfärben ?

**Comment by skvarel** [comment]
@vonCartman .. Du hast bei jedem unsere Widgest die Enstellungen für die Bilder. Dort kannst Du eine Farbe für 'wahr' und eine für 'falsch' festlegen.

![grafik](https://user-images.githubusercontent.com/1114419/111738910-6fef1e80-8882-11eb-8a46-a31febadc33a.png)
