### ISSUE TITLE
Eine Uhr als Icon

### ISSUE THREAD

**Issue by capitaenz** [inventwo/ioBroker.vis-icontwo#114]
Moin Sven,

ich habe grad alles abgesucht, aber keine Uhr als Icon gefunden.
Hab ich das Icon übersehen, oder gibt es wirklich keine?
Hintergrund: Ich möchte mir die Zeit per Knopfdruck ansagen lassen.

VG
Leif

**Comment by skvarel** [comment]
Da ist noch keine Uhr. Mache ich Dir aber gerne moergen fertig.

Gruß, Sven.

**Comment by skvarel** [comment]
@capitaenz 

![grafik](https://user-images.githubusercontent.com/1114419/116805871-a37fc280-ab29-11eb-89d5-4fb910dabdba.png)


.. update kommt heute noch!

**Comment by skvarel** [comment]
Version 0.66.0

![grafik](https://user-images.githubusercontent.com/1114419/116806199-b6939200-ab2b-11eb-8e02-a57a99be85cb.png)

![grafik](https://user-images.githubusercontent.com/1114419/116806218-d460f700-ab2b-11eb-9bae-b248d7552831.png)

**Comment by capitaenz** [comment]
Cool! Danke!  =)
