### ISSUE TITLE
Stripe2  on off deleted?

### ISSUE THREAD

**Issue by fraeggle** [inventwo/ioBroker.vis-icontwo#129]
Hi
I noticed, that there are under Lights no more stripe2_on / stripe3_on / stripe2_off / stripe3_off.
Is that correct?
Using Version 0.69

Regards Peter

**Comment by skvarel** [comment]
Correct.

They were no longer needed because you can rotate them in the widget.

They were removed a long time ago, around version 0.25.0 approximately.

Greetings, Sven.

**Comment by fraeggle** [comment]
:-O  Sorry.... "...They were no longer needed because you can rotate them in the widget...."  must have missed this ...

U are right.. rotate works....   
Thanks...
