### ISSUE TITLE
Fehlende Unterstützung des Farbschemas (Admin5)

### ISSUE THREAD

**Issue by crunchip77** [inventwo/ioBroker.vis-icontwo#178]
Admin 5 Farbschema wird noch nicht unterstützt, da viele das dunkle Design bevorzugen, wäre das wünschenswert, wenn möglich.
icontwo icons
inventwo vis

**Comment by skvarel** [comment]
Wir haben bei dem Icon Adpater gar keine Config, die wir anpassen können.

Die Übersicht ist es eine externe Webseite, die nicht mit dem ioBroker verknüpft ist.

**Comment by crunchip77** [comment]
die Icons Seite ist extern, hatte ich nicht darauf geachtet, die Vis läuft auch extern?
![image](https://user-images.githubusercontent.com/41550245/128679266-9d624a3d-d902-4123-a235-62f633e0fca2.png)

Admin 5 steht ja erst am Anfang, vorher gab es keine Möglichkeit aufs dunkle Design, der Wunsch war aber da und denke das viele nach dem Umstieg auch entsprechend, es nutzen werden.
Ich bin gestern meine Installation durchgegangen und habe für jeden Adapter, der dies noch nicht unterstützt, ein issue erstellt, als Hinweis. Letztendlich ist es nur ein "Schönheitsfehler"

**Comment by jkvarel** [comment]
@crunchip77 
Für vis-inventwo sollte es kein Problem sein dass anzupassen.

Für icontwo werden wir bestimmt auch noch eine Lösung finden
