### ISSUE TITLE
Installation auf Windows Linuxsubsystem Ubuntu nicht möglich.

### ISSUE THREAD

**Issue by TiaBuaNaka** [inventwo/ioBroker.vis-icontwo#183]
Hallo, 
ich habe eine ioBroker Installation auf einem Windows Ubuntu System. Das System und über 20 Adapter laufen einwandfrei, nur den "inventwo Icon Set für ioBroker.vis" bekomme ich nicht installiert. Das ist die Fehlermeldung aus der Installation über "Adapter": 
"
ERROR: Process exited with code 25 

$ iobroker add vis-icontwo --host Server 
NPM version: 6.14.14 
npm install iobroker.vis-icontwo@0.77.0 --loglevel error --prefix "/opt/iobroker" (System call) 
npm ERR! code EACCES 
npm ERR! syscall renamenpm ERR! path /opt/iobroker/node_modules/.staging/npm-a371ebf8/node_modules/string-widthnpm ERR! dest /opt/iobroker/node_modules/.staging/string-width-01f78b50npm ERR! errno -13 
npm ERR! Error: EACCES: permission denied, rename '/opt/iobroker/node_modules/.staging/npm-a371ebf8/node_modules/string-width' -> '/opt/iobroker/node_modules/.staging/string-width-01f78b50'npm ERR! [OperationalError: EACCES: permission denied, rename '/opt/iobroker/node_modules/.staging/npm-a371ebf8/node_modules/string-width' -> '/opt/iobroker/node_modules/.staging/string-width-01f78b50'] {npm ERR! cause: [Error: EACCES: permission denied, rename '/opt/iobroker/node_modules/.staging/npm-a371ebf8/node_modules/string-width' -> '/opt/iobroker/node_modules/.staging/string-width-01f78b50'] { 
npm ERR! errno: -13,npm ERR! code: 'EACCES',npm ERR! syscall: 'rename',npm ERR! path: '/opt/iobroker/node_modules/.staging/npm-a371ebf8/node_modules/string-width',npm ERR! dest: '/opt/iobroker/node_modules/.staging/string-width-01f78b50'npm ERR! },npm ERR! errno: -13,npm ERR! code: 'EACCES',npm ERR! syscall: 'rename',npm ERR! path: '/opt/iobroker/node_modules/.staging/npm-a371ebf8/node_modules/string-width',npm ERR! dest: '/opt/iobroker/node_modules/.staging/string-width-01f78b50',npm ERR! parent: 'iobroker'npm ERR! }npm ERR! npm ERR! The operation was rejected by your operating system.npm ERR! It is likely you do not have the permissions to access this file as the current usernpm ERR! npm ERR! If you believe this might be a permissions issue, please double-check thenpm ERR! permissions of the file and its containing directories, or try runningnpm ERR! the command again as root/Administrator. 
npm ERR! A complete log of this run can be found in:npm ERR! /home/iobroker/.npm/_logs/2021-08-19T14_44_40_982Z-debug.log 
host.Server Cannot install iobroker.vis-icontwo@0.77.0: 243 
ERROR: Process exited with code 25 
"
und das ist der Log über einen Installationsversuch über SSH
"
pi@Server:~$ iobroker stop
Stopping iobroker controller daemon...
iobroker controller daemon stopped.
No "killall.sh" script found. Just stop.
pi@Server:~$ curl -sL https://iobroker.net/fix.sh | bash -
library: loaded
Library version=2021-04-07

==========================================================================

    Welcome to the ioBroker installation fixer!
    Script version: 2021-04-07

    You might need to enter your password a couple of times.

==========================================================================

==========================================================================
    Installing prerequisites (1/3)
==========================================================================

[sudo] password for pi:
Hit:1 http://archive.ubuntu.com/ubuntu focal InRelease
Get:2 http://archive.ubuntu.com/ubuntu focal-updates InRelease [114 kB]
Hit:3 https://deb.nodesource.com/node_14.x focal InRelease
Get:4 http://security.ubuntu.com/ubuntu focal-security InRelease [114 kB]
Get:5 http://archive.ubuntu.com/ubuntu focal-backports InRelease [101 kB]
Get:6 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 Packages [1163 kB]
Get:7 http://archive.ubuntu.com/ubuntu focal-updates/main Translation-en [251 kB]
Get:8 http://security.ubuntu.com/ubuntu focal-security/main amd64 Packages [822 kB]
Get:9 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 c-n-f Metadata [13.9 kB]
Get:10 http://archive.ubuntu.com/ubuntu focal-updates/restricted amd64 Packages [400 kB]
Get:11 http://archive.ubuntu.com/ubuntu focal-updates/restricted Translation-en [57.3 kB]
Get:12 http://archive.ubuntu.com/ubuntu focal-updates/restricted amd64 c-n-f Metadata [480 B]
Get:13 http://archive.ubuntu.com/ubuntu focal-updates/universe amd64 Packages [851 kB]
Get:14 http://archive.ubuntu.com/ubuntu focal-updates/universe Translation-en [179 kB]
Get:15 http://archive.ubuntu.com/ubuntu focal-updates/universe amd64 c-n-f Metadata [18.5 kB]
Get:16 http://archive.ubuntu.com/ubuntu focal-updates/multiverse amd64 Packages [25.0 kB]
Get:17 http://archive.ubuntu.com/ubuntu focal-updates/multiverse Translation-en [6888 B]
Get:18 http://archive.ubuntu.com/ubuntu focal-updates/multiverse amd64 c-n-f Metadata [652 B]
Get:19 http://security.ubuntu.com/ubuntu focal-security/main Translation-en [161 kB]
Get:20 http://security.ubuntu.com/ubuntu focal-security/main amd64 c-n-f Metadata [8440 B]
Get:21 http://security.ubuntu.com/ubuntu focal-security/restricted amd64 Packages [364 kB]
Get:22 http://security.ubuntu.com/ubuntu focal-security/restricted Translation-en [52.1 kB]
Get:23 http://security.ubuntu.com/ubuntu focal-security/restricted amd64 c-n-f Metadata [484 B]
Get:24 http://security.ubuntu.com/ubuntu focal-security/universe amd64 Packages [640 kB]
Get:25 http://security.ubuntu.com/ubuntu focal-security/universe Translation-en [100 kB]
Get:26 http://security.ubuntu.com/ubuntu focal-security/universe amd64 c-n-f Metadata [12.1 kB]
Fetched 5455 kB in 6s (918 kB/s)
Reading package lists... Done
Installed gcc-c++
Installed python-dev

==========================================================================
    Checking ioBroker user and directory permissions (2/3)
==========================================================================

Created /etc/sudoers.d/iobroker
Fixing directory permissions...
This system does not support setting default permissions.
Do not use npm to manually install adapters unless you know what you are doing!

==========================================================================
    Checking autostart (3/3)
==========================================================================

Enabling autostart...

==========================================================================

    Your installation was fixed successfully
    Run iobroker start to start ioBroker again!

==========================================================================

pi@Server:~$ npm i iobroker.vis-icontwo
npm WARN enoent ENOENT: no such file or directory, open '/home/pi/package.json'
npm WARN pi No description
npm WARN pi No repository field.
npm WARN pi No README data
npm WARN pi No license field.

npm ERR! code EACCES
npm ERR! syscall rename
npm ERR! path /home/pi/node_modules/.staging/npm-67dbb18f/node_modules/string-width
npm ERR! dest /home/pi/node_modules/.staging/string-width-3a84e7a4
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, rename '/home/pi/node_modules/.staging/npm-67dbb18f/node_modules/string-width' -> '/home/pi/node_modules/.staging/string-width-3a84e7a4'
npm ERR!  [OperationalError: EACCES: permission denied, rename '/home/pi/node_modules/.staging/npm-67dbb18f/node_modules/string-width' -> '/home/pi/node_modules/.staging/string-width-3a84e7a4'] {
npm ERR!   cause: [Error: EACCES: permission denied, rename '/home/pi/node_modules/.staging/npm-67dbb18f/node_modules/string-width' -> '/home/pi/node_modules/.staging/string-width-3a84e7a4'] {
npm ERR!     errno: -13,
npm ERR!     code: 'EACCES',
npm ERR!     syscall: 'rename',
npm ERR!     path: '/home/pi/node_modules/.staging/npm-67dbb18f/node_modules/string-width',
npm ERR!     dest: '/home/pi/node_modules/.staging/string-width-3a84e7a4'
npm ERR!   },
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'rename',
npm ERR!   path: '/home/pi/node_modules/.staging/npm-67dbb18f/node_modules/string-width',
npm ERR!   dest: '/home/pi/node_modules/.staging/string-width-3a84e7a4'
npm ERR! }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2021-08-19T18_56_08_698Z-debug.log
pi@Server:~$
„
Gruß thomas schwabe

**Comment by Xenon-s** [comment]
@skvarel unter Ubuntu 20.04 kann ich den Fehler nicht reproduzieren. Egal von welcher Version ich auf die 0.77.0 gehe, es geht glatt durch.
Getestet mit node 14.17.5, npm 6.14.14, admin 5.1.24 über admin mehrfach installiert, ebenso über die Konsole

**Comment by TiaBuaNaka** [comment]
@Xenon-s läuft Dein Ubuntu auch als Linuxsubsystem unter Windows oder auf einen Pi oder in einer VM?

**Comment by Xenon-s** [comment]
In einem lxc unter proxmox. Sollte nur ein Hinweis sein

**Comment by skvarel** [comment]
@TiaBuaNaka .. welche nodejs Version hast Du?

**Comment by DutchmanNL** [comment]
ehm npm i iobroker.vis-icontwo auf root Nivea wird NIEMALS gehen

```
cd /opt/iobroker
npm i iobroker.vis-icontwo
```

dan wird klappen

**Comment by skvarel** [comment]
@TiaBuaNaka .. kannst Du den Tipp von @DutchmanNL mal bitte probieren.

**Comment by skvarel** [comment]
Nach dem Fixer sollte es aber auch wieder über die Adpateransicht klappen.

**Comment by TiaBuaNaka** [comment]
@skvarel installiert ist die aktuelle 12er Version.
Der Fix hat, wie Du im Logo sehen kannst, keine Veränderung gebracht. Allerdings konnte er bei meinem System die Ordnerrechte nicht neu setzen, was auch im Log steht.
Den Tipp von DutchmanNL werde ich heute Abend ausprobieren, bin gerade unterwegs.
Danke für die Tipps und Euch einen schönen Start ins Wochenende.

**Comment by skvarel** [comment]
Ich habe den Fehler reproduzieren können! Bei meinem Testsystem lag es an einer 'kaputten' nodejs Version.

Allerdings bei der 14.x.x .... mit der 14.17.4 scheint es Probleme zu geben. Eventuell auch bei der 12er? Wird Dir ein nodejs Update angeboten? Welche 12er hast Du genau?

**Comment by TiaBuaNaka** [comment]
@skvarel da hatte ich wohl was falsch in Erinnerung, die Node.js Version ist bei mir 14.17.5
Der tipp von DutchmanNL hat leider auch nichts gebracht, siehe Log:
2pi@Server:~$ cd /opt/iobroker
pi@Server:/opt/iobroker$ npm i iobroker.vis-icontwo
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: socksv5@https://github.com/christophgysin/socksv5/tarball/7b4eba5b30ecdb6d9e656dcfede1e6884dc7c6d9 (node_modules/socksv5):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Error: EACCES: permission denied, rename '/opt/iobroker/node_modules/.staging/socksv5-5d80f67d/node_modules/ipv6' -> '/opt/iobroker/node_modules/.staging/ipv6-b7792af9'

npm ERR! code EACCES
npm ERR! syscall rename
npm ERR! path /opt/iobroker/node_modules/.staging/npm-a371ebf8/node_modules/string-width
npm ERR! dest /opt/iobroker/node_modules/.staging/string-width-01f78b50
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, rename '/opt/iobroker/node_modules/.staging/npm-a371ebf8/node_modules/string-width' -> '/opt/iobroker/node_modules/.staging/string-width-01f78b50'
npm ERR!  [OperationalError: EACCES: permission denied, rename '/opt/iobroker/node_modules/.staging/npm-a371ebf8/node_modules/string-width' -> '/opt/iobroker/node_modules/.staging/string-width-01f78b50'] {
npm ERR!   cause: [Error: EACCES: permission denied, rename '/opt/iobroker/node_modules/.staging/npm-a371ebf8/node_modules/string-width' -> '/opt/iobroker/node_modules/.staging/string-width-01f78b50'] {
npm ERR!     errno: -13,
npm ERR!     code: 'EACCES',
npm ERR!     syscall: 'rename',
npm ERR!     path: '/opt/iobroker/node_modules/.staging/npm-a371ebf8/node_modules/string-width',
npm ERR!     dest: '/opt/iobroker/node_modules/.staging/string-width-01f78b50'
npm ERR!   },
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'rename',
npm ERR!   path: '/opt/iobroker/node_modules/.staging/npm-a371ebf8/node_modules/string-width',
npm ERR!   dest: '/opt/iobroker/node_modules/.staging/string-width-01f78b50',
npm ERR!   parent: 'iobroker'
npm ERR! }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/iobroker/.npm/_logs/2021-08-20T22_29_40_054Z-debug.log
pi@Server:/opt/iobroker$
"

**Comment by skvarel** [comment]
@DutchmanNL .. hast Du noch eine Idee?

**Comment by Xenon-s** [comment]
Du hast da ein Rechteproblem in deinem System, da kann aber der Adapter nix für. Damals als root das System aufgesetzt? Oder iobroker mit sudo eingerichtet?

**Comment by DutchmanNL** [comment]
> Du hast da ein Rechteproblem in deinem System, da kann aber der Adapter nix für. Damals als root das System aufgesetzt? Oder iobroker mit sudo eingerichtet?

Interessante ist ja das der fixer das gerade biegen sollte 🤔

@TiaBuaNaka 
Mach mal ls -l /opt/iobroker und poste die Ausgabe 

dasselbe da nochmal fürs Verzeichnis opt/iobroker/node_modules/.staging/npm-a371ebf8/node_modules/

**Comment by TiaBuaNaka** [comment]
@DutchmanNL 
Danke für Deine Tipps. Das mit den Rechten ist sicher das Problem, nur habe ich keine Ahnung wie und ob ich das geändert bekomme.
Hier der Log:
pi@Server:~$ ls -l /opt/iobroker
total 404
-rwxrwxrwx 1 iobroker iobroker    676 Aug 20 01:43 INSTALLER_INFO.txt
drwxrwxr-x 1 iobroker iobroker   4096 Aug 22 05:00 backups
drwxrwxrwx 1 iobroker iobroker   4096 Aug 18 14:31 cache
lrwxrwxrwx 1 iobroker iobroker     22 Aug 20 01:43 iob -> /opt/iobroker/iobroker
-rwxr-xr-x 1 iobroker iobroker    188 Aug 20 01:43 iobroker
drwxr-xr-x 1 iobroker iobroker   4096 Aug 23 13:38 iobroker-data
drwxr-xr-x 1 iobroker iobroker   4096 Aug 23 11:01 log
drwxr-xr-x 1 iobroker iobroker   4096 Aug 21 00:29 node_modules
-rw-r--r-- 1 iobroker iobroker 394525 Aug 16 18:58 package-lock.json
-rw-r--r-- 1 iobroker iobroker   2151 Aug 16 18:58 package.json
-rw-r--r-- 1 iobroker iobroker   5693 Aug 15 22:22 reinstall.js
pi@Server:~$ ls -l /opt/iobroker/node_modules/.staging/npm-a371ebf8/node_modules/
ls: cannot access '/opt/iobroker/node_modules/.staging/npm-a371ebf8/node_modules/': No such file or directory
pi@Server:~$

**Comment by DutchmanNL** [comment]
> Danke für Deine Tipps. Das mit den Rechten ist sicher das Problem, nur habe ich keine Ahnung wie und ob ich das geändert bekomme.



genau das. sollte eigentlich der fixer erledigen

**Comment by TiaBuaNaka** [comment]
Bei mir ist der Stand leider unverändert und ich habe noch keine Lösung gefunden. Ich habe 2 ioBroker Systeme am Laufen, das eine auf einem TinkerBoard S (RasPi) und das andere unter Ubuntu als Subsystem von Windows 10. Auf beiden Systemen habe ich die selben über 20 Adapter installiert. Lediglich das iconset bekomme ich auf dem Ubuntu nicht installiert. Wenn ich es über den Browser installieren will bekomme ich immer noch folgende Fehlermeldung:
$ iobroker add vis-icontwo --host Server
NPM version: 6.14.14
npm install iobroker.vis-icontwo@0.82.0 --loglevel error --prefix "/opt/iobroker" (System call)
npm ERR! code EACCES
npm ERR! syscall renamenpm ERR! path /opt/iobroker/node_modules/.staging/npm-a371ebf8/node_modules/string-widthnpm ERR! dest /opt/iobroker/node_modules/.staging/string-width-01f78b50npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, rename '/opt/iobroker/node_modules/.staging/npm-a371ebf8/node_modules/string-width' -> '/opt/iobroker/node_modules/.staging/string-width-01f78b50'npm ERR! [OperationalError: EACCES: permission denied, rename '/opt/iobroker/node_modules/.staging/npm-a371ebf8/node_modules/string-width' -> '/opt/iobroker/node_modules/.staging/string-width-01f78b50'] {npm ERR! cause: [Error: EACCES: permission denied, rename '/opt/iobroker/node_modules/.staging/npm-a371ebf8/node_modules/string-width' -> '/opt/iobroker/node_modules/.staging/string-width-01f78b50'] {npm ERR! errno: -13,
npm ERR! code: 'EACCES',npm ERR! syscall: 'rename',npm ERR! path: '/opt/iobroker/node_modules/.staging/npm-a371ebf8/node_modules/string-width',npm ERR! dest: '/opt/iobroker/node_modules/.staging/string-width-01f78b50'npm ERR! },npm ERR! errno: -13,npm ERR! code: 'EACCES',npm ERR! syscall: 'rename',npm ERR! path: '/opt/iobroker/node_modules/.staging/npm-a371ebf8/node_modules/string-width',npm ERR! dest: '/opt/iobroker/node_modules/.staging/string-width-01f78b50',npm ERR! parent: 'iobroker'npm ERR! }npm ERR! npm ERR! The operation was rejected by your operating system.npm ERR! It is likely you do not have the permissions to access this file as the current usernpm ERR! npm ERR! If you believe this might be a permissions issue, please double-check thenpm ERR! permissions of the file and its containing directories, or try runningnpm ERR! the command again as root/Administrator.
npm ERR! A complete log of this run can be found in:npm ERR! /home/iobroker/.npm/_logs/2021-11-06T10_55_39_304Z-debug.log
host.Server Cannot install iobroker.vis-icontwo@0.82.0: 243
ERROR: Process exited with code 25

Und wenn ich es über die Konsole versuche erhalte ich immer noch diese Fehlermeldung:
pi@Server:~$ npm install iobroker.vis-icontwo
npm WARN enoent ENOENT: no such file or directory, open '/home/pi/package.json'
npm WARN pi No description
npm WARN pi No repository field.
npm WARN pi No README data
npm WARN pi No license field.

npm ERR! code EACCES
npm ERR! syscall rename
npm ERR! path /home/pi/node_modules/.staging/npm-67dbb18f/node_modules/string-width
npm ERR! dest /home/pi/node_modules/.staging/string-width-3a84e7a4
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, rename '/home/pi/node_modules/.staging/npm-67dbb18f/node_modules/string-width' -> '/home/pi/node_modules/.staging/string-width-3a84e7a4'
npm ERR!  [OperationalError: EACCES: permission denied, rename '/home/pi/node_modules/.staging/npm-67dbb18f/node_modules/string-width' -> '/home/pi/node_modules/.staging/string-width-3a84e7a4'] {
npm ERR!   cause: [Error: EACCES: permission denied, rename '/home/pi/node_modules/.staging/npm-67dbb18f/node_modules/string-width' -> '/home/pi/node_modules/.staging/string-width-3a84e7a4'] {
npm ERR!     errno: -13,
npm ERR!     code: 'EACCES',
npm ERR!     syscall: 'rename',
npm ERR!     path: '/home/pi/node_modules/.staging/npm-67dbb18f/node_modules/string-width',
npm ERR!     dest: '/home/pi/node_modules/.staging/string-width-3a84e7a4'
npm ERR!   },
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'rename',
npm ERR!   path: '/home/pi/node_modules/.staging/npm-67dbb18f/node_modules/string-width',                                                                                                                                                                                 
npm ERR!   dest: '/home/pi/node_modules/.staging/string-width-3a84e7a4'
npm ERR! }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2021-11-07T11_04_44_392Z-debug.log

Würde mich über jeden Tipp freuen.

Wünsche Euch noch einen schönen Sonntag.

**Comment by FabianEKS** [comment]
Ich habe dasselbe Problem. Auch bei mir scheitern alle Vorschläge und Versuche den Adapter zu installieren (mit dem Icon Set ist es genauso). (Heute habe ich nochmal auf die neue Node-Version 14.18.2 aktualisiert und nochmal den Fixer laufen lassen --> ohne Erfolg)
Da ich aktuell eine neue Visu aufsetze benötige ich dringend diese Widgets und Icons und brauche an dieser Stelle eure Hilfe.
Ich danke euch schonmal im Voraus für eure Unterstützung und wünsche allen eine erholsame Wiehnachtszeit!

**Comment by skvarel** [comment]
@DutchmanNL  .. hast du noch eine Idee?

**Comment by FabianEKS** [comment]
Heute ein erneuter Versuch. Ich habe mal den Log der Installation als Screenshot angehängt (evtl. hilft das ja).
![grafik](https://user-images.githubusercontent.com/72298450/147466746-667e7e67-99fe-4f7f-a2d7-def6b745f4ae.png)

**Comment by skvarel** [comment]
Bitte jetzt noch mal mit der 0.87.0 versuchen. Wir hatten ab der 0.82.0 einen Fehler im Code.

**Comment by skvarel** [comment]
> Heute ein erneuter Versuch. Ich habe mal den Log der Installation als Screenshot angehängt (evtl. hilft das ja). ![grafik](https://user-images.githubusercontent.com/72298450/147466746-667e7e67-99fe-4f7f-a2d7-def6b745f4ae.png)

Das hat aber nichts mit diesem Adapter zu tun! Dein Screenshot zeigt den vis-inventwo Adapter .... du bist hier aber im Issue vom vis-icontwo Adapter.

**Comment by FabianEKS** [comment]
Hallo,

danke für das Update, das IconSet lies sich jetzt problemlos installieren:
![grafik](https://user-images.githubusercontent.com/72298450/154806279-5bdf59de-3c8c-44be-b234-916732edc093.png)

Zu deiner ANmerkung bzgl. "vis-inventwo" --> nachdem das Problem sowohl am Icon-Set asl auch beim Adapter vorhanden war, ging ich davon aus, dass es sich um dasselbe Problem handelte. --> Auch die Installation des Adapters habe ich soeben erneut gestartet. Auch hier: Installation problemlos.

--> Danke für das Update und die Unterstützung!

**Comment by skvarel** [comment]
Super. Vielen Dank für die Rückmeldung :)

Ich schließe das hier dann jetzt.
