### ISSUE TITLE
Batterieicons Ladestand hinzufügen

### ISSUE THREAD

**Issue by m4ding** [inventwo/ioBroker.vis-icontwo#190]
Hallo,

ich nutze das Icon Set sehr gerne. Wäre es möglich, noch Batterie-Ladestand Icons hinzuzufügen mit Füllgraden von leer, 10%-100% (in 10er Schritten), lädt? 

Danke vorab!
mading

**Comment by m4ding** [comment]
Super vielen Dank für die prompte Antwort! So kann ich für unser e-Auto aber auch verschiedene andere Geräte den Ladestand schön anzeigen lassen. Ich habe mir dazu ein Blockly gebaut, welches aufgrund des Ladestands in % den Pfad des anzuzeigenden Bildes in einen String Datenpunkt schreibt.

**Comment by m4ding** [comment]
Darf ich nach dem Stand der Dinge fragen?

**Comment by skvarel** [comment]
Die ersten sind bei der 0.87.0 online

![image](https://user-images.githubusercontent.com/1114419/154798740-7f37fa25-9b54-4a66-beb8-267e7dafb760.png)

**Comment by m4ding** [comment]
Hi, vielen Dank! 

![grafik](https://user-images.githubusercontent.com/65028008/157628181-1488ec23-2130-437d-87b9-27b19095e35a.png)
