### ISSUE TITLE
Weiße Icons

### ISSUE THREAD

**Issue by tobst96** [inventwo/ioBroker.vis-icontwo#198]
Da meine VIS Farbthema leider nicht mit Schwarzen Icon aussieht, musste ich zur "Konkurrenz" umstellen.

Würde es gut finden, wenn alle Icons in mehreren Farben angeboten werden. (Schwarz/Weiß/Grün/Gelb/Rot).

Am schönsten wäre es, wenn wie in Eurer VIS-Adapter, die Farbe über CCS und ein Datenpunkt eingestellt werden kann. Dann kann z.B. ein Tag / Nacht Style festgelegt werden.

**Comment by skvarel** [comment]
Da die Icons primär für unseren Widget-Adapter gemacht sin und sich dort die Wunschfarbe einfach einstellen lässt, wird es meine Icons nur in Schwarz geben.

Bei unseren Widgest lässt sich jede Einstellung per Datenpunkt regeln. Das mache ich selbst so ;)

Z.B. einfach anstelle der Farbe den Datenpunkt per Binding eintragen. Das klappt auch bei Radien, Rändern usw.

![grafik](https://user-images.githubusercontent.com/1114419/133893269-933a8c88-5859-44c3-8fe0-c5edb14e5bee.png)

**Comment by skvarel** [comment]
Hier mal ein Beispiel von einer meiner Views.

100% inventwo Icons und inverntwo Widgest .. alle Farben werden per Blockly nach bestimmten Uhrzeiten geregelt.

![grafik](https://user-images.githubusercontent.com/1114419/133893312-999c283b-4420-408a-aec5-019a25d293ea.png)

**Comment by skvarel** [comment]
Ein kleiner Ausschnitt meiner Datenpunkte für die VIS:

![grafik](https://user-images.githubusercontent.com/1114419/133893405-fcd63ef0-6c76-44ca-83bc-73eba623b541.png)

Hier regel ich sogar die VIS-Hintergründe per Datenpunkt:

![grafik](https://user-images.githubusercontent.com/1114419/133893437-dc502cb5-b3c7-4892-950c-a8961125468f.png)

**Comment by tobst96** [comment]
Moin. Danke für die schnelle Antwort. Die Datenpunkte verwende ich schon. 

Allerdings finde keine Option die Icon Farbe zu ändern. Auf deinen Screenshots sind diese auch weiß. 
Leider finde ich die Einstellung in der VIS nicht. 

Button, Action und Text stelle ich auch über Datenpunkte ein.

**Comment by skvarel** [comment]
Als HEX:

![grafik](https://user-images.githubusercontent.com/1114419/133906764-b6bc76f5-fdae-470e-98a8-e0e5ec801350.png)

Als Datenpunkt:

![grafik](https://user-images.githubusercontent.com/1114419/133906783-f11f049d-5d9f-4f24-a6bc-16e9f1dd82d8.png)


Den Datenpunkt musst du natürlich selbst anlegen.

**Comment by skvarel** [comment]
Weiß klappt am besten über die Funktion 'invertieren' .. da wird Schwarz zu Weiß umgekehrt.

![grafik](https://user-images.githubusercontent.com/1114419/133906818-1f9d5bbe-e836-40af-9bb4-a0dc171568b9.png)
