### ISSUE TITLE
Neue Icons für die Navigation

### ISSUE THREAD

**Issue by capitaenz** [inventwo/ioBroker.vis-icontwo#212]
Moin Sven,

hast du Lust noch weitere Icons für die Navigation zu erstellen?
/vis-icontwo/Navigations/
![icon](https://user-images.githubusercontent.com/1240236/137587953-2221dd28-a7c9-4115-b4c8-aba48c5db8f5.JPG)

Toll wären Icons mit einem Zahnrad, einem Computer, einer Kamera, ... jeweils im Kreis meine ich.

Viele Grüße
Leif

**Comment by skvarel** [comment]
Ja, kein Problem. Mache ich dir fertig :)

**Comment by skvarel** [comment]
Erledigt. Kommt gleich beim Update.

**Comment by skvarel** [comment]
![grafik](https://user-images.githubusercontent.com/1114419/147743689-3d2dcd98-42db-48ed-a11b-8b1c39015b17.png)


Version 0.85.0
