### ISSUE TITLE
Symbol for thermal heat pump

### ISSUE THREAD

**Issue by Horgul123** [inventwo/ioBroker.vis-icontwo#242]
I would like to have an icon (on/off) for my thermal heat pump for my pool.
Something like this: [https://www.poolsana.de/media/image/5e/a8/a7/wp-ps-inverplus-mit-38mm-anschluss_600x600.jpg](url)

**Comment by skvarel** [comment]
Coming soon to the version 1.2.0

![image](https://github.com/inventwo/ioBroker.vis-icontwo/assets/1114419/d668cdf9-f210-4e9a-8520-87e7af1714f6)
