### ISSUE TITLE
Wetter Icons

### ISSUE THREAD

**Issue by sigi2345** [inventwo/ioBroker.vis-icontwo#3]
Hallo,

könntest du bitte mehr Wettericons hinzufügen.

LG
Sigi234

**Comment by jkvarel** [comment]
@sigi2345 macht @skvarel dir morgen fertig ;)

**Comment by skvarel** [comment]
Kein Problem. Was fehlt Dir genau?

**Comment by sigi2345** [comment]
> Kein Problem. Was fehlt Dir genau?

sun raise
sun_mid	
sun mid
sun_out	
sun set
Sunshine Duration
rain_value	
snowline_value	
wind value
windgusts_value	
windgusts
wind direction
Maximal day temperature
Minimal day temperature
UV-Index
Dewpoint

**Comment by skvarel** [comment]
Ein paar Icons habe ich jetzt umgesetzt. Über die Anderen muss ich mir noch mehr Gedanken machen.

Gruß, Sven.

![grafik](https://user-images.githubusercontent.com/1114419/89005757-881b2900-d305-11ea-8713-3bf8ca228d9e.png)
