### ISSUE TITLE
Add a non-animated icon for fan

### ISSUE THREAD

**Issue by Frickeldave** [inventwo/ioBroker.vis-icontwo#348]
**!!! Before you start !!!!**  
Just found an animated one. 

**Describe wanted Enhancement !**  
I need an icon for a fan which is not animated. I sue that to visualize the speed of the fans in my air handling unit and want to show a "stopped" fan, when ventilation is set to "0".

**Why should we put effort in it ?**  
Let you show a "Stopped" fan.

**Comment by skvarel** [comment]
Devices/Cooling/

Die drei 'off2' Icons kommen mit der 0.93.0 online.

http://icontwo.inventwo.com/Devices/Cooling/
