### ISSUE TITLE
Widgets werden auf iPad nicht dargestellt

### ISSUE THREAD

**Issue by IOMaxOI** [inventwo/ioBroker.vis-icontwo#4]
Hallo,

wenn ich ein VIS mit den Widgets auf dem iPad anschauen will, werden die Widgets nicht dargestellt. Mache ich was falsch oder habt ihr eine Idee woran das liegen könnte?

Edit: Beim neuen iPad Pro sehe ich die Widgets. Mit einem alten 2er leider nicht. Dabei sollte das an die Wand. Bekomme ich das darauf noch zum laufen?

Liebe Grüße
Max

**Comment by skvarel** [comment]
Hallo.

Ich recherchiere das mal. Es gab mal einen Hinweis, dass die alten iPads nicht mehr unterstützt werden. Wir haben hier nur ein aktuelles Pad und da läuft alles.

Benutzt Du einen Browser oder die ioBroker VIS APP?

Gruß, Sven.

**Comment by IOMaxOI** [comment]
Hallo,

klasse. Danke dir schon mal.
Wäre super schade wenn das mit dem alten nicht klappt. Hatte hier nämlich noch zwei rum liegen die dann an die Wand sollten. Was anderes kann man mit denen auch nicht mehr machen. :) 
Und euer Adapter hat so viele tolle Anpassungsmöglichkeiten! Der sollte es eigentlich auf jeden Fall werden...

Ich habe es sowohl über den Browser als auch über die App probiert. Ergebnis war das gleiche. Alle Widgets waren sichtbar - die aus eurem Adapter leider nicht. 

Wäre super falls du was findest.

Vielen Dank und liebe Grüße
Max

**Comment by skvarel** [comment]
Hallo @IOMaxOI 

Besteht das Problem weiterhin? Falls ja, kannst Du bitte ein Issue bei unserem Widget Adapter erstellen? Hier geht es eigentlich nur um die Icons.

https://github.com/inventwo/ioBroker.vis-inventwo/issues

Danke & Gruß, Sven.
