### ISSUE TITLE
Löschen von Icons im Changelog erwähnen

### ISSUE THREAD

**Issue by cratoo** [inventwo/ioBroker.vis-icontwo#40]
Zuerst, danke für die coolen Icons.

Mir ist beim letzten Update allerdings aufgefallen, dass Icons entfernt wurden (vermutlich da sie farblich waren und nicht ins Konzept passten?!) Einerseits schade, andererseits wäre es da schön, das würde im Changelog stehen. Von 0.25 auf 0.26 stand nur etwas vom Hinzufügen und nicht vom Entfernen.

**Comment by skvarel** [comment]
Danke für den Hinweis. Ja, es sind farrbige Icons entfernt worden, da man in unseren Widgets jedes Icon nach Wunsch weinfärben kann.

Es werden in Zukunftr keine Icons mehr entfernt!

**Comment by cratoo** [comment]
> Es werden in Zukunftr keine Icons mehr entfernt und falls es doch nptig sein wird, werde ich es im Log erwähnen.

Das ist ja großartig, dann muss ich gleich mal die Widgets probieren :)
