### ISSUE TITLE
Widgets werden nicht dargestellt

### ISSUE THREAD

**Issue by JWSchumacher** [inventwo/ioBroker.vis-icontwo#5]
Hallo.
Bei Benutzung der App werden die Widgets nicht dargestellt.
Betrifft Samsung Galaxy S9, Samsung Galaxy S9 Plus und Samsung Galaxy Tab 3 @Android 4.2.2
Bei der Darstellung im Browser tritt der Fehler nicht auf.
Mache ich was falsch?
Gruß Joerg

**Comment by skvarel** [comment]
Hallo Joerg.

Nein, Du machst nichts falsch! Die Widgets in der App müssen vom Entwickler der App genehmigt werden. Den Antrag haben wir gestellt und können da nur abwarten.

Gruß, Sven.
