### ISSUE TITLE
Version not updated after installing 0.97.2

### ISSUE THREAD

**Issue by Horgul123** [inventwo/ioBroker.vis-icontwo#523]
After starting the update from 0.97.1 to 0.97.2 it runs wihout any issue.
After the installation the admin still tells me, that V0.97.1 is installed. Tested sveral times

**Comment by skvarel** [comment]
Error found in io-package.json. Will be fixed with 0.79.3.

Thanks!

**Comment by Horgul123** [comment]
You're welcome! Thanks :)

**Comment by Horgul123** [comment]
Can confirm that in 0.97.3 the issue is fixed :)
