### ISSUE TITLE
Icons für "Schere-Stein-Papier"-Spiel

### ISSUE THREAD

**Issue by rtwl21** [inventwo/ioBroker.vis-icontwo#533]
Ich habe mir für die VIS das Spiel Schere-Stein-Papier gemacht, um meine Frau öfters ans Tablet zu "schicken" und sie damit vertrauter wird bzw öfters verwendet. Naja funktioniert nur so semi-gut.
Lange rede kurzer Sinn:
Ich hätte gerne schönere Icons für die 3 Auswahlmöglichkeiten.
Vielleicht habt ihr dazu eine Idee? Zumindest für den "Stein".

So sieht es aktuell aus:
![image](https://github.com/inventwo/ioBroker.vis-icontwo/assets/100233609/c083631f-fc17-4a8e-8075-c2cce6c9ee65)

**Comment by skvarel** [comment]
In der Version 1.1.0 dabei ;)

![image](https://github.com/inventwo/ioBroker.vis-icontwo/assets/1114419/10d772d3-63c1-4705-b58a-a7f4143b367f)
