### ISSUE TITLE
Newspaper / Zeitung

### ISSUE THREAD

**Issue by capitaenz** [inventwo/ioBroker.vis-icontwo#64]
Moin,

eine schöne Sammlung, aber mir fehlt ein Icon für die Zeitung...
Ich habe die Zeitungsrolle überwacht und würde mir dies gerne dem gleichen Stil an Icon(s) anzeigen lassen.
Wäre toll wenn es da etwas gäbe.

VG
Leif

**Comment by skvarel** [comment]
Gute Idee. Mache ich fertig!

**Comment by skvarel** [comment]
Update kommt heute im Laufe des Tages

![grafik](https://user-images.githubusercontent.com/1114419/105678224-2c64dd80-5eed-11eb-8905-ed400a193f22.png)

**Comment by skvarel** [comment]
Die Icons sind in der 0.40.0 (latest) verfügbar, Udapte ist gemacht.
