### ISSUE TITLE
iobroker Error: Cannot upload /opt/iobroker/node_modules/iobroker.vis-icontwo/www/Brands/iobroker.png: Not exists

### ISSUE THREAD

**Issue by GM-Jokemaster** [inventwo/ioBroker.vis-icontwo#659]
It is shown at an Update or File Upload. 
Error: Cannot upload /opt/iobroker/node_modules/iobroker.vis-icontwo/www/Brands/iobroker.png: Not exists

Version: 1.6.3

**Comment by skvarel** [comment]
I don't understand the reason. The icon has been included in my adapter for 4 years.

![grafik](https://github.com/user-attachments/assets/f9408557-b991-4cf8-8a08-838af6c29ff9)

**Comment by skvarel** [comment]
@mcm1957 .. hast du hier eine Idee? Liegt es am Dateinamen? Wird der iobroker.png eventuell wegen den Rechten geblockt? Das war nihct immer so. Das Icon ist seit rund 4 Jahren im Adapter und hat vorher nie Probleme gemacht.

**Comment by mcm1957** [comment]
Eigentlich keine Ahnung.
ABER ev. hilft ein iob fix. Beim js-controller update gabs ein Problem, dass die Ownership im root verbogen wurde. 
Mal schaun welche onwership die Dateien in /opt/iobroker haben

Ansonsten kann ich nur auf Forum und bluefox/foxriver76 verweisen.
Sorry.

**Comment by skvarel** [comment]
Ich habe bei der v1.10.1 das Logo in iob.png umbenannt. Das Update lief bei mir ohne Warnung durch und das Icon wird angezeigt.

![grafik](https://github.com/user-attachments/assets/b37e415b-d2f6-41b2-997e-6e12cec9e79b)
