### ISSUE TITLE
Bewegungsmelder -> Figur / Mensch

### ISSUE THREAD

**Issue by capitaenz** [inventwo/ioBroker.vis-icontwo#67]
Habe da noch ein Anliegen:
Ich würde gerne meine Bewegungsmelder "sichtbar" machen und dafür fehlt auch ein passendes Zeichen.
Ich stelle mir vor, dass bei Bewegung eine Figur mit solch Strichen als angedeutete Bewegung gezeigt wird.
Oder so eine art Strahlen und wenn Bewegung erkannt wird, dann wird eine sich bewegende Figur gezeigt.

Wäre das machbar?

Danke und VG
Leif

**Comment by skvarel** [comment]
Ist machbar! Mache ich Dir fertig :)

**Comment by capitaenz** [comment]
Danke, "Kaffee" ist raus  ;-)

VG
Leif

**Comment by skvarel** [comment]
Danke :)

Morgen früh bekommst Du Deine Icons.

**Comment by skvarel** [comment]
@capitaenz 

![grafik](https://user-images.githubusercontent.com/1114419/106861461-1530a780-66c6-11eb-92e2-bec78485754d.png)

Die Icons findest Du im 'Alarm' Ordner
