### ISSUE TITLE
Neues Icon, für "Brands"

### ISSUE THREAD

**Issue by senger1985** [inventwo/ioBroker.vis-icontwo#97]
Wäre es möglich, "Twitch" unter die Brands mit aufzunehmen?

**Comment by skvarel** [comment]
Ja, ist möglich. Es ist beim nächsten Update im Laufe der Woch drin.

**Comment by senger1985** [comment]
Danke

**Comment by skvarel** [comment]
@senger1985 .. ist in der Version 0.49.0 (latest) enthalten.
