### ISSUE TITLE
Neues Icon, für "Door_Windows"

### ISSUE THREAD

**Issue by senger1985** [inventwo/ioBroker.vis-icontwo#98]
Wäre es möglich, "Gardinen" unter die Door_Windows mit aufzunehmen?(linke Seite/rechte Seite/beide Seiten) Danke

**Comment by skvarel** [comment]
Kein Problem. Mache ich fertig.

**Comment by skvarel** [comment]
@senger1985 

![grafik](https://user-images.githubusercontent.com/1114419/112747120-93694600-8fb3-11eb-8824-9246b1b64710.png)

**Comment by senger1985** [comment]
Vielen Dank, für den schnellen und guten Support

**Comment by skvarel** [comment]
Die Icons sind jetzt bei der 0.50.0 (latest) drin.
